create readme
begemot1987/taxi-service pull request #1
Opened 2021-12-14 17:39 UTC by begemot1987

2021-12-14 20:11 UTC, TankevychO approved these changes

2021-12-15 09:14 UTC, Nick97-git requested changes
- remove redundant `/` from urls like /drivers/, /cars/, /manufacturers/
- at the moment your path looks like src/main/java/mate... We should rename "mate" to something else, like "taxi". After you do that don't forget to change the value you pass to the Injector.getInstance() everywhere you use it
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns
- ConnectionUtil -> add default values for USERNAME, PASSWORD, URL, like "YOUR_URL" for example

2021-12-15 09:14 UTC, Nick97-git commented on README.md
> +   5. Replace `USERNAME` and `PASSWORD` values in `src/main/java/mate/util/ConnectionUtil.java` with your data
what about URL?

2021-12-15 09:14 UTC, Nick97-git commented on README.md
> +replace fileName with absolute path to `.log` file
```suggestion
   6. Change `src/main/resources/log4j2.xml`. Replace fileName with absolute path to your log file at line `<File name="LogToFile" fileName="E:\Mate\Projects\taxi_service\logs\app.log">` 
```

2021-12-15 09:14 UTC, Nick97-git commented on README.md
> +      **WARNING! This script will drop `taxi` schema if you have it. So be careful**
move warning to the next line

2021-12-15 10:47 UTC, Nick97-git approved these changes

2021-12-15 11:48 UTC, merged